export const S = {
  container: { display:'flex', minHeight:'100vh', backgroundColor:'#f8fafc', fontFamily:"'Plus Jakarta Sans', sans-serif", position:'relative', overflow:'hidden' },
  bgOrb1: { position:'fixed', width:'700px', height:'700px', borderRadius:'50%', background:'radial-gradient(circle at 30% 30%, rgba(var(--primary-rgb, 79, 70, 229),0.12), transparent 70%)', top:'-250px', left:'-250px', zIndex:0, animation:'float 25s infinite alternate ease-in-out' },
  bgOrb2: { position:'fixed', width:'550px', height:'550px', borderRadius:'50%', background:'radial-gradient(circle at 70% 70%, rgba(99,102,241,0.12), transparent 70%)', bottom:'-200px', right:'-200px', zIndex:0, animation:'float 30s infinite alternate ease-in-out' },
  bgOrb3: { position:'fixed', width:'400px', height:'400px', borderRadius:'50%', background:'radial-gradient(circle at 50% 50%, rgba(167,139,250,0.1), transparent 70%)', top:'50%', left:'50%', transform:'translate(-50%,-50%)', zIndex:0, animation:'float 20s infinite alternate ease-in-out' },
  mobileMenuBtn: { position:'fixed', top:'16px', left:'16px', zIndex:1001, background:'var(--primary-color, #4f46e5)', color:'#fff', border:'none', borderRadius:'12px', padding:'12px', cursor:'pointer', display:'none', boxShadow:'0 10px 20px -5px rgba(var(--primary-rgb, 79, 70, 229),0.4)' },
  sidebar: { width:'280px', background:'linear-gradient(180deg, #0f172a 0%, #1e1b4b 100%)', color:'#fff', display:'flex', flexDirection:'column', padding:'32px 20px', position:'fixed', height:'100vh', overflowY:'auto', zIndex:99999, boxShadow:'10px 0 30px -10px rgba(0,0,0,0.2)' },
  logoWrapper: { display:'flex', alignItems:'center', gap:'12px', marginBottom:'24px', padding:'0 8px' },
  logoIcon: { background:'linear-gradient(135deg, var(--primary-color, #4f46e5), #818cf8)', padding:'10px', borderRadius:'14px', display:'flex', alignItems:'center', justifyContent:'center', boxShadow:'0 10px 20px -5px rgba(var(--primary-rgb, 79, 70, 229),0.4)' },
  logoText: { fontSize:'1.4rem', fontWeight:'800', letterSpacing:'-0.02em' },
  logoAccent: { color:'#818cf8', marginLeft:'2px' },
  studentBadge: { background:'rgba(var(--primary-rgb, 79, 70, 229),0.2)', borderRadius:'30px', padding:'8px 16px', margin:'0 8px 24px 8px', fontSize:'12px', color:'#a5b4fc', display:'flex', alignItems:'center', gap:'8px', border:'1px solid rgba(255,255,255,0.1)', backdropFilter:'blur(10px)', position:'relative' },
  liveIndicator: { width:'8px', height:'8px', borderRadius:'50%', background:'#22c55e', animation:'pulse 1.5s infinite', position:'absolute', right:'12px' },
  nav: { flex:1, display:'flex', flexDirection:'column', gap:'4px' },
  navLabel: { fontSize:'0.7rem', fontWeight:'800', color:'#94a3b8', padding:'16px 18px 8px', letterSpacing:'0.05em', textTransform:'uppercase' },
  navBtn: { width:'100%', display:'flex', alignItems:'center', gap:'14px', padding:'12px 18px', borderRadius:'16px', border:'none', cursor:'pointer', backgroundColor:'transparent', color:'#94a3b8', fontWeight:'600', textAlign:'left', fontSize:'14px', position:'relative', transition:'all 0.3s ease' },
  navBtnActive: { backgroundColor:'rgba(var(--primary-rgb, 79, 70, 229),0.15)', color:'#fff', boxShadow:'inset 0 2px 4px rgba(0,0,0,0.1)' },
  navBadge: { background:'var(--primary-color, #4f46e5)', color:'#fff', padding:'2px 8px', borderRadius:'30px', fontSize:'10px', fontWeight:'700', marginLeft:'auto' },
  activeIndicator: { position:'absolute', left:0, top:'25%', width:'4px', height:'50%', background:'linear-gradient(180deg, var(--primary-color, #4f46e5), #818cf8)', borderRadius:'0 4px 4px 0' },
  logoutBtn: { display:'flex', alignItems:'center', gap:'12px', padding:'16px 18px', background:'rgba(239,68,68,0.1)', color:'#f87171', border:'1px solid rgba(239,68,68,0.2)', cursor:'pointer', borderRadius:'16px', fontWeight:'700', fontSize:'14px', marginTop:'20px', transition:'all 0.3s ease' },
  main: { flex:1, padding:'48px', marginLeft:'280px', marginRight:'320px', overflowY:'auto', zIndex:5, position:'relative' },
  header: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'40px' },
  title: { fontSize:'2.2rem', fontWeight:'800', margin:0, background:'linear-gradient(135deg, #0f172a, #1e1b4b)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', letterSpacing:'-0.02em' },
  subtitle: { color:'#64748b', marginTop:'6px', fontSize:'1rem', fontWeight:'500' },
  studentName: { color:'var(--primary-color, #4f46e5)', fontWeight:'700' },
  dateBadge: { background:'#fff', padding:'12px 24px', borderRadius:'30px', border:'1px solid #e2e8f0', fontSize:'0.9rem', fontWeight:'700', color:'#1e293b', display:'flex', alignItems:'center', gap:'8px', boxShadow:'0 4px 10px -2px rgba(0,0,0,0.05)' },
  overviewContainer: { display:'flex', flexDirection:'column', gap:'32px' },
  statsGrid: { display:'grid', gridTemplateColumns:'repeat(4, 1fr)', gap:'20px' },
  metricCard: { background:'#fff', padding:'20px', borderRadius:'24px', border:'1px solid #e2e8f0', display:'flex', alignItems:'center', gap:'16px', transition:'all 0.3s ease', boxShadow:'0 4px 6px -2px rgba(0,0,0,0.05)' },
  metricIconWrapper: (color) => {
    let bg = `${color}15`;
    if (color.startsWith('#') && color.length === 7) {
      const r = parseInt(color.slice(1,3), 16);
      const g = parseInt(color.slice(3,5), 16);
      const b = parseInt(color.slice(5,7), 16);
      bg = `rgba(${r}, ${g}, ${b}, 0.15)`;
    }
    return { width:'48px', height:'48px', borderRadius:'16px', background:bg, display:'flex', alignItems:'center', justifyContent:'center', color };
  },
  metricLabel: { margin:0, fontSize:'0.75rem', fontWeight:'600', color:'#64748b', letterSpacing:'0.02em' },
  metricValue: { margin:'2px 0 0', fontSize:'1.6rem', fontWeight:'800' },
  metricTrend: { fontSize:'0.65rem', fontWeight:'600', color:'#22c55e', background:'#dcfce7', padding:'2px 8px', borderRadius:'30px', display:'inline-block' },
  chartCard: { background:'#fff', padding:'24px', borderRadius:'28px', border:'1px solid #e2e8f0', boxShadow:'0 10px 25px -5px rgba(0,0,0,0.05)' },
  chartHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'16px' },
  chartTitle: { margin:0, fontWeight:'700', fontSize:'1.1rem', color:'#0f172a' },
  chartSubtitle: { margin:'4px 0 0', fontSize:'0.8rem', color:'#64748b' },
  chartControls: { display:'flex', alignItems:'center', gap:'8px', background:'#f1f5f9', padding:'6px 14px', borderRadius:'30px' },
  chartLive: { fontSize:'0.7rem', fontWeight:'700', color:'var(--primary-color, #4f46e5)', letterSpacing:'0.05em' },
  classInfoCard: { background:'#fff', padding:'24px', borderRadius:'28px', border:'1px solid #e2e8f0' },
  classInfoHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'16px' },
  classInfoTitle: { margin:0, fontWeight:'700', fontSize:'1.1rem', color:'#0f172a' },
  classInfoSubtitle: { margin:'4px 0 0', fontSize:'0.85rem', color:'#64748b' },
  classBadge: { background:'#dbeafe', color:'#1e40af', padding:'6px 16px', borderRadius:'30px', fontSize:'0.75rem', fontWeight:'700' },
  classSubjectsGrid: { display:'flex', flexWrap:'wrap', gap:'10px', marginBottom:'16px' },
  subjectPill: { background:'#f1f5f9', padding:'8px 16px', borderRadius:'30px', fontSize:'0.85rem', fontWeight:'600', color:'#0f172a', display:'flex', alignItems:'center', gap:'6px' },
  viewScheduleBtn: { background:'none', border:'none', color:'var(--primary-color, #4f46e5)', fontWeight:'700', fontSize:'0.9rem', cursor:'pointer', display:'flex', alignItems:'center', gap:'4px', padding:'8px 0' },
  alertCard: { background:'#fffbeb', border:'1px solid #fcd34d', borderRadius:'24px', padding:'20px', display:'flex', alignItems:'center', gap:'16px' },
  alertContent: { flex:1 },
  alertTitle: { margin:0, fontSize:'1rem', fontWeight:'700', color:'#92400e' },
  alertText: { margin:'4px 0 0', fontSize:'0.85rem', color:'#b45309' },
  alertBtn: { background:'var(--primary-color, #4f46e5)', color:'#fff', border:'none', padding:'10px 20px', borderRadius:'30px', fontWeight:'700', fontSize:'0.85rem', cursor:'pointer' },
  recentActivityCard: { background:'#fff', padding:'24px', borderRadius:'28px', border:'1px solid #e2e8f0' },
  recentHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'16px' },
  recentTitle: { margin:0, fontWeight:'700', fontSize:'1rem', color:'#0f172a' },
  activityList: { display:'flex', flexDirection:'column', gap:'12px' },
  activityItem: { display:'flex', alignItems:'center', gap:'12px', padding:'8px 0', borderBottom:'1px solid #f1f5f9' },
  activityDot: { width:'8px', height:'8px', borderRadius:'50%', background:'var(--primary-color, #4f46e5)' },
  activityContent: { flex:1 },
  activityCourse: { display:'block', fontSize:'0.9rem', fontWeight:'600', color:'#0f172a' },
  activityDate: { fontSize:'0.7rem', color:'#94a3b8' },
  activityStatus: { padding:'4px 10px', borderRadius:'20px', fontSize:'0.7rem', fontWeight:'700', textTransform:'uppercase' },
  attendanceStatsGrid: { display:'grid', gridTemplateColumns:'repeat(4, 1fr)', gap:'20px', marginBottom:'32px' },
  attendanceStatCard: { background:'#fff', padding:'20px', borderRadius:'20px', border:'1px solid #e2e8f0', textAlign:'center' },
  statLabel: { fontSize:'0.7rem', fontWeight:'700', color:'#64748b', marginBottom:'4px' },
  statValue: { fontSize:'1.8rem', fontWeight:'800', color:'#0f172a' },
  tableCard: { background:'#fff', borderRadius:'28px', border:'1px solid #e2e8f0', overflow:'hidden', marginBottom:'24px' },
  tableHeader: { padding:'20px 24px', borderBottom:'1px solid #f1f5f9' },
  tableTitle: { margin:0, fontWeight:'700', fontSize:'1rem', color:'#0f172a' },
  tableContainer: { overflowX:'auto' },
  table: { width:'100%', borderCollapse:'collapse', minWidth:'600px' },
  tableHeadRow: { background:'#f8fafc', borderBottom:'1px solid #e2e8f0' },
  th: { padding:'14px 24px', color:'#64748b', fontSize:'0.7rem', fontWeight:'800', textAlign:'left', letterSpacing:'0.05em' },
  tableRow: { borderBottom:'1px solid #f1f5f9', transition:'background 0.2s ease' },
  tdName: { padding:'18px 24px', fontWeight:'700', color:'#1e1b4b', fontSize:'0.95rem', textTransform:'capitalize' },
  td: { padding:'16px 24px', color:'#64748b', fontSize:'0.85rem', fontWeight:'500' },
  emptyTableCell: { padding:'40px', textAlign:'center', color:'#94a3b8' },
  statusBadge: { padding:'4px 12px', borderRadius:'20px', fontSize:'0.7rem', fontWeight:'700', display:'inline-block' },
  sectionTitle: { fontSize:'1.3rem', fontWeight:'800', marginBottom:'24px', color:'#0f172a' },
  gradesSummary: { display:'flex', gap:'32px', marginBottom:'32px', padding:'28px', background:'linear-gradient(135deg, #1e1b4b, #312e81)', borderRadius:'32px', border:'1px solid rgba(255,255,255,0.1)', boxShadow:'0 20px 40px -15px rgba(30,27,75,0.2)' },
  summaryItem: { display:'flex', flexDirection:'column', gap:'6px' },
  gradeBadge: { background:'#10b981', color:'#fff', padding:'6px 14px', borderRadius:'10px', fontWeight:'800', fontSize:'0.85rem', boxShadow:'0 4px 10px rgba(16,185,129,0.2)' },
  tabContainer: { display:'flex', gap:'24px', marginBottom:'24px', paddingBottom:'8px', borderBottom:'1px solid #e2e8f0' },
  tabBtn: { background:'none', border:'none', cursor:'pointer', fontSize:'1rem', fontWeight:'700', padding:'8px 0' },
  emptyState: { textAlign:'center', padding:'60px 20px', background:'#fff', borderRadius:'24px', border:'1px solid #e2e8f0', color:'#94a3b8' },
  classesGrid: { display:'grid', gridTemplateColumns:'repeat(auto-fill, minmax(280px, 1fr))', gap:'20px' },
  classCard: { background:'#fff', padding:'20px', borderRadius:'24px', border:'1px solid #e2e8f0', transition:'all 0.3s ease' },
  className: { fontSize:'1.1rem', fontWeight:'700', color:'#0f172a', margin:'0 0 4px' },
  classInfo: { fontSize:'0.85rem', color:'#64748b', margin:'0 0 8px' },
  classTeacher: { fontSize:'0.85rem', color:'#64748b', display:'flex', alignItems:'center', gap:'4px', marginBottom:'0' },
  registerBtn: { padding:'10px 20px', borderRadius:'20px', border:'none', fontWeight:'700', fontSize:'0.85rem', cursor:'pointer', color:'#fff', textAlign:'center' },
  coursesGrid: { display:'grid', gridTemplateColumns:'repeat(auto-fill, minmax(260px, 1fr))', gap:'20px' },
  courseCard: { background:'#fff', padding:'20px', borderRadius:'24px', border:'1px solid #e2e8f0', transition:'all 0.3s ease' },
  courseCardHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'16px' },
  courseIcon: { width:'48px', height:'48px', borderRadius:'16px', background:'linear-gradient(135deg, var(--primary-color, #4f46e5), #818cf8)', display:'flex', alignItems:'center', justifyContent:'center' },
  courseTitle: { fontSize:'1rem', fontWeight:'700', color:'#0f172a', margin:'0 0 8px' },
  courseDesc: { fontSize:'0.8rem', color:'#64748b', margin:'0 0 16px', lineHeight:'1.5' },
  courseFooter: { display:'flex', alignItems:'center', gap:'6px', fontSize:'0.8rem', color:'#64748b', marginBottom:'16px' },
  availableTag: { background:'#dcfce7', color:'#166534', padding:'4px 10px', borderRadius:'20px', fontSize:'0.7rem', fontWeight:'700', border:'1px solid #b9f6ca' },
  enrollBtn: { width:'100%', padding:'12px', borderRadius:'20px', background:'linear-gradient(135deg, var(--primary-color, #4f46e5), #818cf8)', color:'#fff', border:'none', fontWeight:'700', cursor:'pointer', fontSize:'0.85rem', transition:'all 0.2s ease' },
  backBtn: { display:'inline-flex', alignItems:'center', gap:'8px', background:'none', border:'none', color:'var(--primary-color, #4f46e5)', fontWeight:'700', cursor:'pointer', fontSize:'0.9rem', marginBottom:'20px', padding:'8px 0' },
  detailCard: { background:'#fff', padding:'32px', borderRadius:'28px', border:'1px solid #e2e8f0' },
  detailTitle: { fontSize:'1.5rem', fontWeight:'800', color:'#0f172a', marginBottom:'12px' },
  detailDesc: { color:'#64748b', marginBottom:'24px', lineHeight:'1.7' },
  detailInstructor: { display:'flex', alignItems:'center', gap:'12px', padding:'16px', background:'#f8fafc', borderRadius:'16px' },
  timetableContainer: { padding:'20px' },
  daySection: { marginBottom:'24px' },
  dayHeading: { fontSize:'1rem', fontWeight:'800', color:'#1e293b', marginBottom:'12px' },
  timetableSlot: { display:'flex', justifyContent:'space-between', alignItems:'center', padding:'14px 20px', background:'#fff', borderRadius:'16px', border:'1px solid #e2e8f0', marginBottom:'8px', borderLeft:'4px solid var(--primary-color, #4f46e5)' },
  timetableCourseTitle: { fontSize:'1rem', fontWeight:'700', color:'#0f172a' },
  roomInfo: { display:'flex', alignItems:'center', gap:'4px', fontSize:'0.75rem', color:'#64748b', marginTop:'4px' },
  roomBadge: { padding:'4px 12px', borderRadius:'20px', background:'#e0e7ff', color:'#4338ca', fontSize:'0.75rem', fontWeight:'700' },
  assignmentsList: { padding:'20px', display:'flex', flexDirection:'column', gap:'16px' },
  assignmentCard: { background:'#fff', padding:'24px', borderRadius:'24px', border:'1px solid #e2e8f0', boxShadow: '0 4px 20px -5px rgba(0,0,0,0.05)', transition: 'transform 0.2s ease, box-shadow 0.2s ease' },
  assignmentHeader: { display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:'12px' },
  assignmentCourse: { display:'block', fontSize:'0.75rem', fontWeight:'700', color:'var(--primary-color, #4f46e5)', marginBottom:'4px' },
  assignmentDue: { display:'block', fontSize:'0.75rem', color:'#94a3b8' },
  scoreBadge: { background:'#0f172a', color:'#fff', padding:'4px 12px', borderRadius:'8px', fontWeight:'800', fontSize:'0.85rem' },
  assignmentTitle: { fontSize:'1.1rem', fontWeight:'800', color:'#0f172a', margin:'0 0 10px', letterSpacing:'-0.01em' },
  assignmentDesc: { fontSize:'0.85rem', color:'#64748b', margin:'0 0 16px', lineHeight:'1.5' },
  feedbackBox: { background:'#f8fafc', padding:'12px 16px', borderRadius:'12px', marginBottom:'16px', border:'1px solid #f1f5f9' },
  feedbackLabel: { fontWeight:'700', fontSize:'0.8rem', color:'var(--primary-color, #4f46e5)', margin:'0 0 4px' },
  feedbackText: { fontSize:'0.85rem', color:'#475569', margin:0 },
  submitBtn: { width:'100%', padding:'12px', borderRadius:'20px', border:'none', fontWeight:'700', cursor:'pointer', fontSize:'0.85rem', transition:'all 0.2s ease' },
  rightPanel: { width:'300px', position:'fixed', right:0, top:0, height:'100vh', overflowY:'auto', padding:'32px 24px', background:'linear-gradient(180deg, #fff, #f8fafc)', borderLeft:'1px solid #e2e8f0', zIndex:10 },
  profileCard: { background:'linear-gradient(135deg, #f5f3ff, #fff)', padding:'24px', borderRadius:'28px', border:'1px solid #e2e8f0', marginBottom:'20px', textAlign:'center' },
  avatar: { width:'64px', height:'64px', borderRadius:'20px', background:'linear-gradient(135deg, var(--primary-color, #4f46e5), #818cf8)', color:'#fff', display:'flex', alignItems:'center', justifyContent:'center', fontSize:'28px', fontWeight:'800', margin:'0 auto 12px', boxShadow:'0 10px 25px -8px rgba(var(--primary-rgb, 79, 70, 229),0.3)' },
  profileName: { fontWeight:'800', fontSize:'1.1rem', color:'#0f172a', margin:'0 0 6px' },
  idBadge: { background:'#e0e7ff', color:'#4338ca', padding:'4px 12px', borderRadius:'20px', fontSize:'0.75rem', fontWeight:'700', display:'inline-block', marginBottom:'8px' },
  profileStats: { display:'flex', justifyContent:'space-around', marginTop:'16px', paddingTop:'16px', borderTop:'1px solid #f1f5f9' },
  profileStat: { textAlign:'center', fontSize:'0.75rem', color:'#64748b', fontWeight:'600' },
  notificationCard: { background:'#fff', padding:'20px', borderRadius:'24px', border:'1px solid #e2e8f0', marginBottom:'20px' },
  notificationHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'16px' },
  notificationList: { display:'flex', flexDirection:'column', gap:'12px' },
  notificationItem: { display:'flex', alignItems:'flex-start', gap:'10px' },
  notificationDot: { width:'8px', height:'8px', borderRadius:'50%', background:'var(--primary-color, #4f46e5)', marginTop:'5px', flexShrink:0 },
  notificationText: { margin:'0 0 2px', fontSize:'0.8rem', color:'#0f172a', fontWeight:'600' },
  notificationTime: { fontSize:'0.7rem', color:'#94a3b8' },
  upcomingCard: { background:'#fff', padding:'20px', borderRadius:'24px', border:'1px solid #e2e8f0' },
  upcomingTitle: { fontWeight:'700', fontSize:'0.9rem', color:'#0f172a', margin:'0 0 16px' },
  upcomingItem: { display:'flex', alignItems:'center', gap:'10px', padding:'10px 0', borderBottom:'1px solid #f1f5f9', fontSize:'0.8rem', color:'#475569', fontWeight:'500' },
  modalOverlay: { position:'fixed', inset:0, background:'rgba(15,23,42,0.7)', backdropFilter:'blur(8px)', display:'flex', alignItems:'center', justifyContent:'center', zIndex:9999 },
  modal: { background:'#fff', padding:'32px', borderRadius:'32px', width:'460px', maxHeight:'85vh', overflowY:'auto', boxShadow:'0 40px 60px -20px rgba(0,0,0,0.3)' },
  modalHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'20px' },
  modalTitle: { fontWeight:'800', fontSize:'1.2rem', color:'#0f172a', margin:0 },
  modalClose: { background:'#f1f5f9', border:'none', width:'36px', height:'36px', borderRadius:'50%', fontSize:'1.3rem', cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', color:'#64748b' },
  modalSubtitle: { color:'#64748b', marginTop:'-12px', marginBottom:'20px', fontSize:'0.9rem' },
  modalForm: { display:'flex', flexDirection:'column', gap:'16px' },
  inputGroup: { display:'flex', flexDirection:'column', gap:'6px' },
  inputLabel: { fontSize:'0.85rem', fontWeight:'700', color:'#475569' },
  textarea: { padding:'12px 16px', borderRadius:'16px', border:'2px solid #f1f5f9', outline:'none', width:'100%', fontSize:'0.9rem', fontFamily:"'Plus Jakarta Sans', sans-serif", minHeight:'120px', resize:'vertical', boxSizing:'border-box' },
  fileUpload: { border:'2px dashed #e2e8f0', borderRadius:'16px', padding:'24px', textAlign:'center', cursor:'pointer', transition:'all 0.2s ease' },
  uploadText: { margin:'8px 0 0', fontSize:'0.85rem', color:'#64748b' },
  modalActions: { display:'flex', gap:'12px', marginTop:'8px' },
  cancelBtn: { flex:1, padding:'12px', background:'#f1f5f9', border:'none', borderRadius:'30px', cursor:'pointer', fontWeight:'700', color:'#64748b', fontSize:'0.9rem' },
  saveBtn: { flex:2, padding:'12px', background:'linear-gradient(135deg, var(--primary-color, #4f46e5), #818cf8)', color:'#fff', border:'none', borderRadius:'30px', cursor:'pointer', fontWeight:'700', fontSize:'0.9rem', boxShadow:'0 8px 20px -8px rgba(var(--primary-rgb, 79, 70, 229),0.5)' },
};
