// ==================== TEACHER SHARED STYLES ====================
export const S = {
  container: { display:'flex', minHeight:'100vh', backgroundColor:'#f8fafc', fontFamily:"'Plus Jakarta Sans', sans-serif", position:'relative', overflow:'hidden' },
  bgOrb1: { position:'fixed', width:'700px', height:'700px', borderRadius:'50%', background:'radial-gradient(circle at 30% 30%, rgba(79,70,229,0.1), transparent 70%)', top:'-250px', left:'-250px', zIndex:0, animation:'float 25s infinite alternate ease-in-out' },
  bgOrb2: { position:'fixed', width:'550px', height:'550px', borderRadius:'50%', background:'radial-gradient(circle at 70% 70%, rgba(99,102,241,0.1), transparent 70%)', bottom:'-200px', right:'-200px', zIndex:0, animation:'float 30s infinite alternate ease-in-out' },
  bgOrb3: { position:'fixed', width:'400px', height:'400px', borderRadius:'50%', background:'radial-gradient(circle at 50% 50%, rgba(129,140,248,0.08), transparent 70%)', top:'50%', left:'50%', transform:'translate(-50%,-50%)', zIndex:0, animation:'float 20s infinite alternate ease-in-out' },
  mobileMenuBtn: { position:'fixed', top:'16px', left:'16px', zIndex:1001, background:'#4f46e5', color:'#fff', border:'none', borderRadius:'12px', padding:'12px', cursor:'pointer', display:'none', boxShadow:'0 10px 20px -5px rgba(79,70,229,0.4)' },
  sidebar: { width:'280px', background:'linear-gradient(180deg, #1e1b4b 0%, #312e81 100%)', color:'#fff', display:'flex', flexDirection:'column', padding:'32px 20px', position:'fixed', height:'100vh', overflowY:'auto', zIndex:10, boxShadow:'10px 0 30px -10px rgba(0,0,0,0.2)' },
  logoWrapper: { display:'flex', alignItems:'center', gap:'12px', marginBottom:'24px', padding:'0 8px' },
  logoIcon: { width:'40px', height:'40px', background:'rgba(255,255,255,0.1)', borderRadius:'12px', display:'flex', alignItems:'center', justifyContent:'center', color:'#fff' },
  logoText: { fontSize:'1.4rem', fontWeight:'800', letterSpacing:'0.05em', color:'#fff', textTransform:'uppercase' },
  logoAccent: { color:'#a5b4fc', marginLeft:'4px' },
  userBadge: { background:'rgba(255,255,255,0.05)', borderRadius:'30px', padding:'10px 20px', margin:'0 8px 32px 8px', fontSize:'13px', color:'#fff', display:'flex', alignItems:'center', gap:'12px', border:'1px solid rgba(255,255,255,0.1)', backdropFilter:'blur(10px)', position:'relative' },
  liveIndicator: { width:'10px', height:'10px', borderRadius:'50%', background:'#22c55e', animation:'pulse 1.5s infinite', position:'absolute', right:'16px', boxShadow:'0 0 10px #22c55e' },
  nav: { flex:1, display:'flex', flexDirection:'column', gap:'4px' },
  navBtn: { width:'100%', display:'flex', alignItems:'center', gap:'14px', padding:'14px 20px', borderRadius:'16px', border:'none', cursor:'pointer', backgroundColor:'transparent', color:'rgba(255,255,255,0.7)', fontWeight:'600', textAlign:'left', fontSize:'15px', position:'relative', transition:'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)' },
  navBtnActive: { backgroundColor:'rgba(255,255,255,0.1)', color:'#fff' },
  navBadge: { background:'#7c3aed', color:'#fff', padding:'2px 10px', borderRadius:'30px', fontSize:'12px', fontWeight:'800', minWidth:'20px', textAlign:'center', boxShadow:'0 4px 10px rgba(0,0,0,0.1)' },
  activeIndicator: { position:'absolute', left:0, top:'20%', width:'4px', height:'60%', background:'#fff', borderRadius:'0 4px 4px 0', boxShadow:'0 0 15px #fff' },
  logoutBtn: { display:'flex', alignItems:'center', gap:'12px', padding:'14px 16px', background:'rgba(239,68,68,0.1)', color:'#f87171', border:'1px solid rgba(239,68,68,0.2)', cursor:'pointer', borderRadius:'14px', fontWeight:'700', fontSize:'14px', marginTop:'16px', transition:'all 0.3s ease' },
  main: { flex:1, padding:'40px 48px', marginLeft:'280px', overflowY:'auto', zIndex:5, position:'relative' },
  header: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'36px' },
  headerActions: { display:'flex', gap:'12px', alignItems:'center' },
  title: { fontSize:'2rem', fontWeight:'800', margin:0, background:'linear-gradient(135deg, #1e1b4b, #312e81)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', letterSpacing:'-0.02em' },
  subtitle: { color:'#64748b', marginTop:'6px', fontSize:'0.95rem', fontWeight:'500' },
  teacherName: { color:'#4f46e5', fontWeight:'700' },
  dateBadge: { background:'#fff', padding:'10px 20px', borderRadius:'30px', border:'1px solid #e2e8f0', fontSize:'0.9rem', fontWeight:'700', color:'#1e293b', display:'flex', alignItems:'center', gap:'8px', boxShadow:'0 4px 10px -2px rgba(0,0,0,0.05)' },
  statsGrid: { display:'grid', gridTemplateColumns:'repeat(4, 1fr)', gap:'20px', marginBottom:'28px' },
  metricCard: { backgroundColor:'#fff', padding:'20px', borderRadius:'24px', border:'1px solid #e2e8f0', display:'flex', alignItems:'center', gap:'14px', transition:'all 0.3s ease', boxShadow:'0 4px 6px -2px rgba(0,0,0,0.05)' },
  metricIconWrapper: (color) => ({ width:'48px', height:'48px', borderRadius:'16px', background:`${color}15`, display:'flex', alignItems:'center', justifyContent:'center', color }),
  metricLabel: { margin:0, fontSize:'0.8rem', fontWeight:'600', color:'#64748b', letterSpacing:'0.02em' },
  metricValue: { margin:'2px 0', fontSize:'1.7rem', fontWeight:'800' },
  metricTrend: { fontSize:'0.7rem', fontWeight:'600', color:'#22c55e', background:'#dcfce7', padding:'2px 8px', borderRadius:'30px', display:'inline-block' },
  chartCard: { backgroundColor:'#fff', padding:'28px', borderRadius:'32px', border:'1px solid #e2e8f0', boxShadow:'0 10px 25px -5px rgba(0,0,0,0.05)', marginBottom:'28px' },
  chartHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'20px' },
  chartTitle: { margin:0, fontWeight:'700', fontSize:'1.2rem', color:'#0f172a' },
  chartSubtitle: { margin:'4px 0 0', fontSize:'0.85rem', color:'#64748b' },
  chartControls: { display:'flex', alignItems:'center', gap:'8px', background:'#f1f5f9', padding:'6px 14px', borderRadius:'30px' },
  chartLive: { fontSize:'0.75rem', fontWeight:'700', color:'#4f46e5', letterSpacing:'0.05em' },
  bottomGrid: { display:'grid', gridTemplateColumns:'1fr 1fr', gap:'24px', marginBottom:'24px' },
  quickActionsCard: { backgroundColor:'#fff', padding:'24px', borderRadius:'24px', border:'1px solid #e2e8f0' },
  scheduleCard: { backgroundColor:'#fff', padding:'24px', borderRadius:'24px', border:'1px solid #e2e8f0' },
  sectionHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'16px' },
  sectionTitle: { margin:'0 0 16px', fontWeight:'700', fontSize:'1rem', color:'#0f172a' },
  actionsGrid: { display:'grid', gridTemplateColumns:'1fr 1fr', gap:'10px' },
  primarySmallBtn: { padding:'12px', borderRadius:'14px', border:'none', background:'linear-gradient(135deg, #4f46e5, #6366f1)', color:'#fff', fontWeight:'700', fontSize:'0.85rem', cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', gap:'8px', transition:'all 0.2s ease' },
  secondarySmallBtn: { padding:'12px', borderRadius:'14px', border:'1px solid #e2e8f0', background:'#f8fafc', color:'#1e293b', fontWeight:'700', fontSize:'0.85rem', cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', gap:'8px', transition:'all 0.2s ease' },
  scheduleList: { display:'flex', flexDirection:'column', gap:'12px' },
  scheduleItem: { display:'flex', alignItems:'center', gap:'12px', padding:'10px', background:'#f8fafc', borderRadius:'14px' },
  scheduleTime: { fontSize:'0.8rem', fontWeight:'800', color:'#4f46e5', minWidth:'50px' },
  scheduleInfo: { flex:1, display:'flex', flexDirection:'column' },
  scheduleCourse: { fontSize:'0.9rem', fontWeight:'700', color:'#0f172a' },
  scheduleRoom: { fontSize:'0.75rem', color:'#64748b' },
  emptySchedule: { color:'#94a3b8', fontSize:'0.9rem', textAlign:'center', padding:'20px' },
  pendingAlert: { background:'linear-gradient(135deg, #fff7ed, #fff)', border:'1px solid #fed7aa', borderRadius:'20px', padding:'16px 20px', display:'flex', alignItems:'center', gap:'12px', marginTop:'20px' },
  viewBtn: { background:'#f97316', color:'#fff', border:'none', padding:'8px 16px', borderRadius:'20px', fontWeight:'700', fontSize:'0.85rem', cursor:'pointer', marginLeft:'auto' },
  tableCard: { backgroundColor:'#fff', borderRadius:'32px', border:'1px solid #e2e8f0', overflow:'hidden', boxShadow:'0 10px 25px -5px rgba(0,0,0,0.05)' },
  tableHeader: { padding:'24px 28px', display:'flex', justifyContent:'space-between', alignItems:'center', borderBottom:'1px solid #f1f5f9' },
  tableTitle: { margin:0, fontWeight:'700', fontSize:'1.2rem', color:'#0f172a' },
  tableSubtitle: { margin:'4px 0 0', fontSize:'0.85rem', color:'#64748b' },
  addBtn: { background:'linear-gradient(135deg, #4f46e5, #6366f1)', color:'#fff', border:'none', padding:'12px 24px', borderRadius:'30px', cursor:'pointer', fontWeight:'700', fontSize:'0.9rem', display:'flex', alignItems:'center', gap:'8px', transition:'all 0.3s ease', boxShadow:'0 10px 20px -8px rgba(79,70,229,0.5)' },
  table: { width:'100%', borderCollapse:'collapse', minWidth:'600px' },
  tableHeadRow: { borderBottom:'1px solid #e2e8f0' },
  th: { padding:'16px 28px', backgroundColor:'#f8fafc', color:'#64748b', fontSize:'0.75rem', fontWeight:'800', letterSpacing:'0.05em', textAlign:'left' },
  tableRow: { borderBottom:'1px solid #f1f5f9', transition:'background 0.2s ease' },
  tdName: { padding:'18px 28px', fontWeight:'700', color:'#0f172a', fontSize:'0.95rem' },
  td: { padding:'18px 28px', color:'#64748b', fontSize:'0.9rem', fontWeight:'500' },
  iconBtn: { background:'none', border:'none', color:'#64748b', cursor:'pointer', padding:'8px', borderRadius:'10px', transition:'all 0.2s ease', display:'inline-flex', alignItems:'center', justifyContent:'center' },
  deleteIconBtn: { background:'none', border:'none', color:'#ef4444', cursor:'pointer', padding:'8px', borderRadius:'10px', transition:'all 0.2s ease', display:'inline-flex', alignItems:'center', justifyContent:'center' },
  actionGroup: { display:'flex', gap:'8px', justifyContent:'flex-end' },
  statusBadge: { padding:'4px 10px', borderRadius:'30px', fontSize:'0.7rem', fontWeight:'700', textTransform:'uppercase', display:'inline-block' },
  emptyState: { textAlign:'center', padding:'60px 20px', color:'#94a3b8' },
  emptyTableCell: { padding:'32px', textAlign:'center', color:'#94a3b8', fontSize:'0.9rem' },
  emptyMessage: { textAlign:'center', color:'#94a3b8', padding:'24px' },
  backButton: { background:'#f1f5f9', border:'1px solid #e2e8f0', padding:'10px 20px', borderRadius:'20px', cursor:'pointer', fontWeight:'700', color:'#64748b', fontSize:'0.9rem', marginBottom:'16px', display:'inline-flex', alignItems:'center', gap:'8px', transition:'all 0.2s ease' },
  classesGrid: { display:'grid', gridTemplateColumns:'repeat(auto-fill, minmax(260px, 1fr))', gap:'20px', padding:'24px' },
  classCard: { background:'linear-gradient(135deg, #f8fafc, #fff)', borderRadius:'24px', border:'1px solid #e2e8f0', padding:'24px', cursor:'pointer', transition:'all 0.3s ease', boxShadow:'0 4px 12px rgba(0,0,0,0.04)' },
  classCardHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'12px' },
  classYearBadge: { fontSize:'11px', fontWeight:'700', background:'#ede9fe', color:'#5b21b6', padding:'4px 10px', borderRadius:'20px' },
  classStudentCount: { fontSize:'13px', fontWeight:'700', color:'#64748b', display:'flex', alignItems:'center', gap:'4px' },
  className: { fontSize:'1.2rem', fontWeight:'800', color:'#0f172a', margin:'0 0 4px' },
  classSection: { fontSize:'0.85rem', color:'#64748b', margin:'0 0 12px' },
  classFooter: { display:'flex', justifyContent:'space-between', alignItems:'center' },
  classCoursesCount: { fontSize:'12px', fontWeight:'700', color:'#4f46e5', display:'flex', alignItems:'center', gap:'4px' },
  coursesList: { padding:'24px' },
  listSubtitle: { fontWeight:'700', fontSize:'0.9rem', color:'#64748b', marginBottom:'16px', textTransform:'uppercase', letterSpacing:'0.05em' },
  gradesFilter: { padding:'16px 28px', borderBottom:'1px solid #f1f5f9' },
  modernSelect: { padding:'12px 20px', borderRadius:'20px', border:'2px solid #f1f5f9', fontSize:'0.9rem', fontWeight:'600', color:'#1e293b', background:'#f8fafc', cursor:'pointer', width:'100%', maxWidth:'400px', outline:'none' },
  gradesSummary: { display:'flex', gap:'24px', padding:'16px 28px', borderBottom:'1px solid #f1f5f9', background:'#fafbff' },
  summaryItem: { display:'flex', flexDirection:'column', gap:'4px', fontSize:'0.85rem', color:'#64748b', fontWeight:'600' },
  examType: { padding:'3px 8px', borderRadius:'8px', background:'#ede9fe', color:'#5b21b6', fontSize:'0.75rem', fontWeight:'700' },
  gradeBadge: { padding:'4px 10px', borderRadius:'20px', background:'#dcfce7', color:'#166534', fontSize:'0.8rem', fontWeight:'800' },
  assignmentGrid: { display:'grid', gridTemplateColumns:'repeat(auto-fill, minmax(320px, 1fr))', gap:'20px', padding:'24px' },
  assignmentCard: { background:'#fff', borderRadius:'24px', border:'1px solid #e2e8f0', padding:'20px', cursor:'pointer', transition:'all 0.3s ease', boxShadow:'0 4px 12px rgba(0,0,0,0.04)', display:'flex', flexDirection:'column', gap:'16px' },
  assignmentCardHeader: { display:'flex', flexDirection:'column', gap:'8px' },
  assignmentTags: { display:'flex', gap:'8px', alignItems:'center' },
  tagHomework: { padding:'4px 10px', borderRadius:'8px', background:'#ede9fe', color:'#5b21b6', fontSize:'0.75rem', fontWeight:'700', display:'flex', alignItems:'center', gap:'4px' },
  tagPublished: { padding:'4px 10px', borderRadius:'8px', background:'#dcfce7', color:'#166534', fontSize:'0.75rem', fontWeight:'700', display:'flex', alignItems:'center', gap:'4px' },
  assignmentCardTitle: { fontSize:'1.05rem', fontWeight:'800', color:'#0f172a', margin:0 },
  assignmentCardInfo: { display:'flex', justifyContent:'space-between', alignItems:'center' },
  dueInfo: { display:'flex', alignItems:'center', gap:'10px' },
  dueIconWrapper: { width:'36px', height:'36px', borderRadius:'12px', background:'#f1f5f9', display:'flex', alignItems:'center', justifyContent:'center', color:'#64748b' },
  submissionCounterBox: { padding:'6px 14px', borderRadius:'20px', background:'#f1f5f9', fontSize:'0.8rem', fontWeight:'700', color:'#64748b' },
  assignmentCardActions: { display:'flex', gap:'10px', borderTop:'1px solid #f1f5f9', paddingTop:'12px' },
  viewSubBtn: { flex:1, padding:'10px', borderRadius:'14px', border:'none', background:'#4f46e5', color:'#fff', fontWeight:'700', fontSize:'0.85rem', cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', gap:'6px', transition:'all 0.2s ease' },
  editAssignBtn: { padding:'10px 16px', borderRadius:'14px', border:'1px solid #e2e8f0', background:'#fff', color:'#64748b', fontWeight:'700', fontSize:'0.85rem', cursor:'pointer', display:'flex', alignItems:'center', gap:'6px', transition:'all 0.2s ease' },
  submissionsView: { padding:'24px' },
  submissionsLayout: { display:'grid', gridTemplateColumns:'260px 1fr', gap:'20px', minHeight:'500px' },
  studentList: { display:'flex', flexDirection:'column', gap:'8px' },
  studentItem: (active) => ({ padding:'16px', borderRadius:'16px', border:'1px solid', borderColor: active ? '#4f46e5' : '#f1f5f9', background: active ? '#f5f3ff' : '#fff', cursor:'pointer', transition:'all 0.2s ease', display:'flex', justifyContent:'space-between', alignItems:'center', boxShadow: active ? '0 4px 12px rgba(79,70,229,0.1)' : 'none' }),
  studentItemInfo: { display:'flex', flexDirection:'column', gap:'2px' },
  studentItemName: { fontSize:'0.9rem', fontWeight:'700', color:'#0f172a' },
  studentItemId: { fontSize:'0.75rem', color:'#64748b' },
  studentItemDate: { fontSize:'0.7rem', color:'#94a3b8', marginTop:'4px' },
  submissionSplitView: { display:'grid', gridTemplateColumns:'280px 1fr', gap:'24px', minHeight:'600px', marginTop:'24px' },
  studentListPane: { background:'#fff', borderRadius:'24px', border:'1px solid #e2e8f0', overflowY:'auto', maxHeight:'700px' },
  gradingPane: { background:'#fff', borderRadius:'24px', border:'1px solid #e2e8f0', overflowY:'auto', maxHeight:'700px', padding:'32px' },
  submissionContent: { display:'flex', flexDirection:'column', gap:'24px' },
  paneHeader: { padding:'20px 24px', borderBottom:'1px solid #f1f5f9', background:'#fafbff', borderRadius:'24px 24px 0 0' },
  paneTitle: { margin:0, fontSize:'1rem', fontWeight:'700', color:'#0f172a' },
  gradingHeader: { display:'flex', justifyContent:'space-between', alignItems:'flex-start', paddingBottom:'24px', borderBottom:'1px solid #f1f5f9' },
  gradableInfo: { display:'flex', flexDirection:'column', gap:'4px' },
  gradableName: { fontSize:'1.4rem', fontWeight:'800', color:'#0f172a', margin:0 },
  gradableSubText: { fontSize:'0.85rem', color:'#64748b', margin:0 },
  statusText: { textAlign:'right', fontSize:'0.8rem', color:'#64748b', fontWeight:'600', lineHeight:1.5 },
  contentSection: { display:'flex', flexDirection:'column', gap:'12px', marginTop:'24px' },
  sectionLabel: { fontSize:'0.85rem', fontWeight:'800', color:'#1e293b', display:'flex', alignItems:'center', gap:'8px', textTransform:'uppercase', letterSpacing:'0.05em' },
  textSubmission: { background:'#f8fafc', padding:'20px', borderRadius:'16px', border:'1px solid #e2e8f0', fontSize:'0.95rem', lineHeight:1.6, color:'#334155', whiteSpace:'pre-wrap' },
  attachmentCard: { display:'flex', alignItems:'center', gap:'16px', padding:'16px', background:'#fff', border:'1px solid #e2e8f0', borderRadius:'16px', transition:'all 0.2s ease' },
  fileIcon: { width:'48px', height:'48px', borderRadius:'12px', background:'#f1f5f9', display:'flex', alignItems:'center', justifyContent:'center', color:'#4f46e5' },
  filePreview: { marginTop:'12px', borderRadius:'16px', overflow:'hidden', border:'1px solid #e2e8f0', background:'#f8fafc', display:'flex', justifyContent:'center' },
  previewImg: { maxWidth:'100%', maxHeight:'400px', objectFit:'contain' },
  gradingForm: { marginTop:'32px', padding:'32px', background:'#f8fafc', borderRadius:'24px', border:'1px solid #e2e8f0', display:'flex', flexDirection:'column', gap:'20px' },
  row: { display:'flex', gap:'20px' },
  submissionPanel: { background:'#f8fafc', borderRadius:'20px', padding:'24px' },
  timetableContainer: { overflowX:'auto' },
  timetableGrid: { display:'grid', gridTemplateColumns:'repeat(7, 1fr)', gap:'16px', padding:'20px', background:'#f8fafc', borderRadius:'24px', minWidth:'900px' },
  dayColumn: { display:'flex', flexDirection:'column', gap:'10px' },
  dayTitle: { fontSize:'0.85rem', fontWeight:'800', color:'#1e293b', textAlign:'center', padding:'10px', background:'#fff', borderRadius:'14px', boxShadow:'0 4px 6px -1px rgba(0,0,0,0.05)', border:'1px solid #f1f5f9' },
  timetableEntry: { background:'#fff', padding:'12px', borderRadius:'16px', boxShadow:'0 4px 12px rgba(0,0,0,0.03)', border:'1px solid #f1f5f9', borderLeft:'4px solid #4f46e5' },
  entryTime: { fontSize:'0.7rem', fontWeight:'700', color:'#4f46e5', marginBottom:'4px' },
  entryCourse: { fontSize:'0.85rem', fontWeight:'800', color:'#0f172a', marginBottom:'2px' },
  entryRoom: { fontSize:'0.7rem', color:'#94a3b8' },
  noEntry: { fontSize:'0.7rem', color:'#94a3b8', textAlign:'center', padding:'12px', background:'#f8fafc', borderRadius:'12px', border:'1px dashed #e2e8f0' },
  labTable: { width:'100%', borderCollapse:'collapse', minWidth:'700px' },
  profileContainer: { maxWidth:'700px' },
  profileCard: { background:'linear-gradient(135deg, #f5f3ff, #fff)', borderRadius:'32px', padding:'36px', border:'1px solid #e2e8f0', marginBottom:'24px' },
  profileAvatarLarge: { width:'90px', height:'90px', borderRadius:'28px', background:'linear-gradient(135deg, #4f46e5, #818cf8)', color:'#fff', display:'flex', alignItems:'center', justifyContent:'center', fontSize:'36px', fontWeight:'800', marginBottom:'16px', boxShadow:'0 15px 30px -10px rgba(79,70,229,0.3)' },
  profileName: { fontSize:'1.6rem', fontWeight:'800', color:'#0f172a', margin:'0 0 4px' },
  profileEmail: { fontSize:'0.95rem', color:'#64748b', margin:'0 0 16px' },
  roleBadge: { padding:'6px 16px', borderRadius:'30px', fontSize:'0.8rem', fontWeight:'700', background:'#ede9fe', color:'#4f46e5', display:'inline-block', marginBottom:'20px' },
  profileStats: { display:'flex', gap:'24px', paddingTop:'16px', borderTop:'1px solid #f1f5f9' },
  profileStatItem: { textAlign:'center' },
  profileStatValue: { fontSize:'1.5rem', fontWeight:'800', color:'#4f46e5' },
  profileStatLabel: { fontSize:'0.75rem', color:'#64748b', fontWeight:'600' },
  approveBtn: { background:'#22c55e', color:'#fff', border:'none', padding:'8px 16px', borderRadius:'30px', fontWeight:'600', fontSize:'0.8rem', cursor:'pointer', display:'inline-flex', alignItems:'center', gap:'6px', transition:'all 0.2s ease', boxShadow:'0 4px 10px -2px rgba(34,197,94,0.3)' },
  rejectBtn: { background:'#ef4444', color:'#fff', border:'none', padding:'8px 16px', borderRadius:'30px', fontWeight:'600', fontSize:'0.8rem', cursor:'pointer', display:'inline-flex', alignItems:'center', gap:'6px', transition:'all 0.2s ease', boxShadow:'0 4px 10px -2px rgba(239,68,68,0.3)' },
  modalOverlay: { position:'fixed', inset:0, background:'rgba(15,23,42,0.7)', backdropFilter:'blur(8px)', display:'flex', alignItems:'center', justifyContent:'center', zIndex:9999, animation:'fadeIn 0.2s ease' },
  modal: { background:'#fff', padding:'36px', borderRadius:'36px', width:'460px', maxHeight:'90vh', overflowY:'auto', boxShadow:'0 50px 70px -20px rgba(0,0,0,0.3)' },
  modalHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'24px' },
  modalTitle: { fontWeight:'800', fontSize:'1.4rem', color:'#0f172a', letterSpacing:'-0.02em', margin:0 },
  modalClose: { background:'#f1f5f9', border:'none', width:'40px', height:'40px', borderRadius:'50%', fontSize:'1.5rem', cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', color:'#64748b', transition:'all 0.2s ease' },
  modalForm: { display:'flex', flexDirection:'column', gap:'16px' },
  inputGroup: { display:'flex', flexDirection:'column', gap:'6px' },
  inputLabel: { fontSize:'0.85rem', fontWeight:'700', color:'#475569', marginLeft:'4px' },
  input: { padding:'12px 16px', borderRadius:'16px', border:'2px solid #f1f5f9', outline:'none', width:'100%', fontSize:'0.9rem', fontWeight:'500', transition:'all 0.2s ease', boxSizing:'border-box', fontFamily:"'Plus Jakarta Sans', sans-serif" },
  modalActions: { display:'flex', gap:'12px', marginTop:'8px' },
  cancelBtn: { flex:1, padding:'14px', background:'#f1f5f9', border:'none', borderRadius:'30px', cursor:'pointer', fontWeight:'700', color:'#64748b', fontSize:'0.9rem', transition:'all 0.2s ease' },
  saveBtn: { flex:2, padding:'14px', background:'linear-gradient(135deg, #4f46e5, #6366f1)', color:'#fff', border:'none', borderRadius:'30px', cursor:'pointer', fontWeight:'700', fontSize:'0.9rem', transition:'all 0.2s ease', boxShadow:'0 10px 20px -8px rgba(79,70,229,0.5)' },
  loadingContainer: { height:'100vh', display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center', gap:'16px', background:'#f8fafc' },
  loadingSpinner: { width:'50px', height:'50px', border:'4px solid #e2e8f0', borderTop:'4px solid #4f46e5', borderRadius:'50%', animation:'spin 1s linear infinite' },
};
