// ==================== SUPERADMIN SHARED STYLES ====================
export const S = {
  container: { 
    display: 'flex', 
    minHeight: '100vh', 
    backgroundColor: '#f8fafc', 
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    position: 'relative',
    overflow: 'hidden',
  },
  bgOrb1: {
    position: 'fixed',
    width: '600px',
    height: '600px',
    borderRadius: '50%',
    background: 'radial-gradient(circle at 30% 30%, rgba(var(--primary-rgb, 79, 70, 229), 0.15), transparent 70%)',
    top: '-200px',
    left: '-200px',
    zIndex: 0,
    animation: 'float 20s infinite alternate ease-in-out',
  },
  bgOrb2: {
    position: 'fixed',
    width: '500px',
    height: '500px',
    borderRadius: '50%',
    background: 'radial-gradient(circle at 70% 70%, rgba(124, 58, 237, 0.15), transparent 70%)',
    bottom: '-150px',
    right: '-150px',
    zIndex: 0,
    animation: 'float 25s infinite alternate ease-in-out',
  },
  sidebar: { 
    width: '280px', 
    background: 'linear-gradient(180deg, #0f172a 0%, #1e1b4b 100%)',
    color: '#fff', 
    display: 'flex', 
    flexDirection: 'column', 
    padding: '32px 20px', 
    position: 'fixed', 
    height: '100vh', 
    overflowY: 'auto',
    zIndex: 10,
    boxShadow: '10px 0 30px -10px rgba(0,0,0,0.2)',
  },
  logoWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '24px',
    padding: '0 8px',
  },
  logoIcon: {
    background: 'linear-gradient(135deg, var(--primary-color, #4f46e5), #7c3aed)',
    padding: '10px',
    borderRadius: '14px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 10px 20px -5px rgba(var(--primary-rgb, 79, 70, 229), 0.4)',
  },
  logoText: {
    fontSize: '1.4rem',
    fontWeight: '800',
    letterSpacing: '-0.02em',
  },
  logoAccent: {
    color: '#818cf8',
    marginLeft: '2px',
  },
  globalBadge: {
    background: 'rgba(var(--primary-rgb, 79, 70, 229), 0.2)',
    borderRadius: '30px',
    padding: '8px 16px',
    margin: '0 8px 24px 8px',
    fontSize: '12px',
    color: '#a5b4fc',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    border: '1px solid rgba(255,255,255,0.1)',
    backdropFilter: 'blur(10px)',
  },
  nav: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  navBtn: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    padding: '14px 18px',
    borderRadius: '16px',
    border: 'none',
    cursor: 'pointer',
    backgroundColor: 'transparent',
    color: '#94a3b8',
    fontWeight: '600',
    textAlign: 'left',
    fontSize: '15px',
    position: 'relative',
    transition: 'all 0.3s ease',
  },
  navBtnActive: {
    backgroundColor: 'rgba(var(--primary-rgb, 79, 70, 229), 0.15)',
    color: '#fff',
    boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.1)',
  },
  activeIndicator: {
    position: 'absolute',
    left: 0,
    top: '25%',
    width: '4px',
    height: '50%',
    background: 'linear-gradient(180deg, var(--primary-color, #4f46e5), #818cf8)',
    borderRadius: '0 4px 4px 0',
  },
  logoutBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '16px 18px',
    background: 'rgba(239, 68, 68, 0.1)',
    color: '#f87171',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    cursor: 'pointer',
    borderRadius: '16px',
    fontWeight: '700',
    fontSize: '15px',
    marginTop: '20px',
    transition: 'all 0.3s ease',
  },
  main: { 
    flex: 1, 
    padding: '48px', 
    marginLeft: '280px', 
    marginRight: '320px', 
    overflowY: 'auto',
    zIndex: 5,
    position: 'relative',
  },
  header: { 
    display: 'flex', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    marginBottom: '40px',
  },
  title: { 
    fontSize: '2.2rem', 
    fontWeight: '800', 
    margin: 0,
    background: 'linear-gradient(135deg, #0f172a, #1e1b4b)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    letterSpacing: '-0.02em',
  },
  subtitle: { 
    color: '#64748b', 
    marginTop: '6px', 
    fontSize: '1rem',
    fontWeight: '500',
  },
  campusCounter: {
    background: '#fff',
    padding: '12px 24px',
    borderRadius: '30px',
    border: '1px solid #e2e8f0',
    fontSize: '0.95rem',
    fontWeight: '700',
    color: 'var(--primary-color, #4f46e5)',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    boxShadow: '0 4px 10px -2px rgba(0,0,0,0.05)',
  },
  overviewContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '32px',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '24px',
  },
  metricCard: {
    backgroundColor: '#fff',
    padding: '24px',
    borderRadius: '28px',
    border: '1px solid #e2e8f0',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 6px -2px rgba(0,0,0,0.05)',
  },
  metricIconWrapper: (color) => ({
    width: '56px',
    height: '56px',
    borderRadius: '20px',
    background: `${color}15`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: color,
  }),
  metricLabel: { 
    margin: 0, 
    fontSize: '0.9rem', 
    fontWeight: '600', 
    color: '#64748b',
    letterSpacing: '0.02em',
  },
  metricValue: { 
    margin: '4px 0 0', 
    fontSize: '2rem', 
    fontWeight: '800',
  },
  chartCard: {
    backgroundColor: '#fff',
    padding: '28px',
    borderRadius: '32px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 10px 25px -5px rgba(0,0,0,0.05)',
  },
  chartHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
  },
  chartTitle: {
    margin: 0,
    fontWeight: '700',
    fontSize: '1.2rem',
    color: '#0f172a',
  },
  chartLegend: {
    display: 'flex',
    gap: '16px',
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '0.9rem',
    fontWeight: '600',
    color: '#475569',
  },
  legendDot: {
    width: '10px',
    height: '10px',
    borderRadius: '4px',
  },
  tableCard: {
    backgroundColor: '#fff',
    borderRadius: '32px',
    border: '1px solid #e2e8f0',
    overflow: 'hidden',
    boxShadow: '0 10px 25px -5px rgba(0,0,0,0.05)',
  },
  tableHeader: {
    padding: '24px 28px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid #f1f5f9',
  },
  tableTitle: {
    margin: 0,
    fontWeight: '700',
    fontSize: '1.2rem',
    color: '#0f172a',
  },
  tableBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '6px 14px',
    background: '#f1f5f9',
    borderRadius: '30px',
    fontSize: '0.8rem',
    fontWeight: '600',
    color: '#475569',
  },
  tableContainer: {
    overflowX: 'auto',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    minWidth: '700px',
  },
  th: {
    padding: '16px 20px',
    backgroundColor: '#f8fafc',
    color: '#64748b',
    fontSize: '0.7rem',
    fontWeight: '800',
    letterSpacing: '0.05em',
    textAlign: 'left',
    borderBottom: '1px solid #e2e8f0',
  },
  tr: {
    borderBottom: '1px solid #f1f5f9',
    transition: 'background 0.2s ease',
  },
  tdName: {
    padding: '20px 28px',
    fontWeight: '700',
    color: '#0f172a',
    fontSize: '0.95rem',
  },
  td: {
    padding: '16px 20px',
    color: '#64748b',
    fontSize: '0.85rem',
    fontWeight: '500',
  },
  planBadge: {
    padding: '4px 12px',
    borderRadius: '30px',
    fontSize: '0.75rem',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: '0.03em',
  },
  statusBadge: {
    padding: '4px 12px',
    borderRadius: '30px',
    fontSize: '0.75rem',
    fontWeight: '700',
  },
  campusTag: {
    padding: '4px 12px',
    borderRadius: '30px',
    background: '#f0fdf4',
    color: '#166534',
    fontSize: '0.75rem',
    fontWeight: '700',
  },
  actionButtons: {
    display: 'flex',
    gap: '8px',
    justifyContent: 'flex-end',
  },
  editBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--primary-color, #4f46e5)',
    cursor: 'pointer',
    padding: '8px',
    borderRadius: '10px',
    transition: 'all 0.2s ease',
  },
  deleteBtn: {
    background: 'none',
    border: 'none',
    color: '#ef4444',
    cursor: 'pointer',
    padding: '8px',
    borderRadius: '10px',
    transition: 'all 0.2s ease',
  },
  addBtn: {
    background: 'linear-gradient(135deg, var(--primary-color, #4f46e5), #7c3aed)',
    color: '#fff',
    border: 'none',
    padding: '12px 24px',
    borderRadius: '30px',
    cursor: 'pointer',
    fontWeight: '700',
    fontSize: '0.9rem',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'all 0.3s ease',
    boxShadow: '0 10px 20px -8px rgba(var(--primary-rgb, 79, 70, 229), 0.5)',
  },
  rightPanel: {
    width: '320px',
    backgroundColor: '#fff',
    borderLeft: '1px solid #e2e8f0',
    padding: '40px 24px',
    position: 'fixed',
    right: 0,
    top: 0,
    height: '100vh',
    overflowY: 'auto',
    zIndex: 10,
    boxShadow: '-10px 0 30px -10px rgba(0,0,0,0.05)',
  },
  profileCard: {
    textAlign: 'center',
    background: 'linear-gradient(135deg, #f8fafc, #ffffff)',
    padding: '32px 20px',
    borderRadius: '32px',
    border: '1px solid #e2e8f0',
    marginBottom: '32px',
  },
  avatar: {
    width: '80px',
    height: '80px',
    color: '#fff',
    borderRadius: '28px',
    margin: '0 auto 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '32px',
    fontWeight: '800',
    boxShadow: '0 15px 30px -10px rgba(var(--primary-rgb, 79, 70, 229), 0.3)',
  },
  profileName: {
    margin: '0 0 8px',
    fontSize: '1.2rem',
    fontWeight: '800',
    color: '#0f172a',
  },
  roleBadge: {
    padding: '6px 16px',
    borderRadius: '30px',
    fontSize: '0.8rem',
    fontWeight: '700',
    background: '#e0e7ff',
    color: '#3730a3',
    display: 'inline-block',
  },
  profileStats: {
    marginTop: '24px',
    paddingTop: '20px',
    borderTop: '1px solid #f1f5f9',
  },
  profileStat: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '12px',
  },
  profileStatLabel: {
    fontSize: '0.85rem',
    color: '#64748b',
    fontWeight: '600',
  },
  profileStatValue: {
    fontSize: '0.85rem',
    fontWeight: '700',
    color: '#0f172a',
  },
  platformStats: {
    marginTop: '32px',
  },
  platformStatsTitle: {
    fontWeight: '700',
    marginBottom: '20px',
    fontSize: '1rem',
    color: '#0f172a',
  },
  platformStatItem: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '14px 0',
    borderBottom: '1px solid #f1f5f9',
  },
  platformStatLabel: {
    fontSize: '0.9rem',
    color: '#64748b',
    fontWeight: '600',
  },
  platformStatValue: {
    fontWeight: '800',
    fontSize: '1rem',
  },
  systemStatus: {
    marginTop: '32px',
    padding: '16px',
    background: '#f0fdf4',
    borderRadius: '20px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    color: '#166534',
    fontSize: '0.9rem',
    fontWeight: '600',
  },
  systemStatusDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    background: '#22c55e',
    animation: 'pulse 2s infinite',
  },
  overlay: { 
    position: 'fixed', 
    inset: 0, 
    background: 'rgba(15, 23, 42, 0.7)', 
    backdropFilter: 'blur(8px)',
    display: 'flex', 
    alignItems: 'center', 
    justifyContent: 'center', 
    zIndex: 1000,
    animation: 'fadeIn 0.2s ease',
  },
  modal: { 
    background: '#fff', 
    padding: '0', 
    borderRadius: '24px', 
    width: '540px', 
    maxHeight: '90vh', 
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 25px 50px -12px rgba(0,0,0,0.25)',
    animation: 'slideUp 0.3s ease',
  },
  modalHeader: {
    padding: '20px 32px',
    borderBottom: '1px solid #e2e8f0',
    background: '#f8fafc',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopLeftRadius: '24px',
    borderTopRightRadius: '24px',
  },
  modalClose: {
    background: '#f1f5f9',
    border: 'none',
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    fontSize: '1.2rem',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#64748b',
    transition: 'all 0.2s ease',
  },
  modalTitle: {
    fontWeight: '700',
    fontSize: '1.25rem',
    color: '#0f172a',
    letterSpacing: '-0.01em',
    margin: 0,
  },
  modalForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    padding: '24px 32px 32px 32px',
    overflowY: 'auto',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  inputLabel: {
    fontSize: '0.85rem',
    fontWeight: '700',
    color: '#475569',
    marginLeft: '4px',
  },
  input: { 
    padding: '10px 14px', 
    borderRadius: '12px', 
    border: '2px solid #e2e8f0', 
    outline: 'none', 
    width: '100%', 
    fontSize: '0.9rem',
    fontWeight: '500',
    transition: 'all 0.2s ease',
    boxSizing: 'border-box',
    color: '#1e293b',
  },
  checkboxGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '8px 0',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
    accentColor: 'var(--primary-color, #4f46e5)',
  },
  checkboxLabel: {
    fontSize: '0.95rem',
    fontWeight: '600',
    color: '#0f172a',
    cursor: 'pointer',
  },
  modalActions: {
    display: 'flex',
    gap: '12px',
    marginTop: '12px',
  },
  cancelBtn: { 
    padding: '10px 20px', 
    background: '#f1f5f9', 
    border: 'none', 
    borderRadius: '12px', 
    cursor: 'pointer', 
    fontWeight: '600', 
    color: '#475569',
    fontSize: '0.9rem',
    transition: 'all 0.2s ease',
  },
  saveBtn: { 
    padding: '10px 20px', 
    background: 'linear-gradient(135deg, var(--primary-color, #4f46e5), #7c3aed)', 
    color: '#fff', 
    border: 'none', 
    borderRadius: '12px', 
    cursor: 'pointer', 
    fontWeight: '600',
    fontSize: '0.9rem',
    transition: 'all 0.2s ease',
    boxShadow: '0 4px 14px rgba(var(--primary-rgb, 79, 70, 229), 0.3)',
  },
  infoItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    padding: '12px',
    background: '#f8fafc',
    borderRadius: '12px',
    marginBottom: '8px',
    border: '1px solid #e2e8f0'
  },
  infoLabel: {
    fontSize: '0.7rem',
    fontWeight: '700',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: '2px'
  },
  infoValue: {
    fontSize: '0.9rem',
    fontWeight: '700',
    color: '#0f172a'
  },
  loadingContainer: {
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '16px',
    background: '#f8fafc',
  },
  loadingSpinner: {
    width: '50px',
    height: '50px',
    border: '4px solid #e2e8f0',
    borderTop: '4px solid var(--primary-color, #4f46e5)',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  loadingText: {
    fontSize: '1rem',
    fontWeight: '600',
    color: 'var(--primary-color, #4f46e5)',
  },
  modalFooter: {
    padding: '20px 32px',
    background: '#f8fafc',
    borderTop: '1px solid #e2e8f0',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    borderRadius: '0 0 32px 32px'
  },
  submitBtn: {
    padding: '12px 24px',
    borderRadius: '12px',
    border: 'none',
    color: '#fff',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 10px 20px -8px rgba(0,0,0,0.2)'
  }
};
