// ==================== HOD/PRINCIPAL SHARED STYLES ====================
export const S = {
  container: { display:'flex', minHeight:'100vh', backgroundColor:'#f8fafc', fontFamily:"'Plus Jakarta Sans', sans-serif", position:'relative', overflow:'hidden' },
  bgOrb1: { position:'fixed', width:'700px', height:'700px', borderRadius:'50%', background:'radial-gradient(circle at 30% 30%, rgba(124,58,237,0.12), transparent 70%)', top:'-250px', left:'-250px', zIndex:0, animation:'float 25s infinite alternate ease-in-out' },
  bgOrb2: { position:'fixed', width:'550px', height:'550px', borderRadius:'50%', background:'radial-gradient(circle at 70% 70%, rgba(167,139,250,0.12), transparent 70%)', bottom:'-200px', right:'-200px', zIndex:0, animation:'float 30s infinite alternate ease-in-out' },
  bgOrb3: { position:'fixed', width:'400px', height:'400px', borderRadius:'50%', background:'radial-gradient(circle at 50% 50%, rgba(196,181,253,0.1), transparent 70%)', top:'50%', left:'50%', transform:'translate(-50%,-50%)', zIndex:0, animation:'float 20s infinite alternate ease-in-out' },
  mobileMenuBtn: { position:'fixed', top:'16px', left:'16px', zIndex:1001, background:'#7c3aed', color:'#fff', border:'none', borderRadius:'12px', padding:'12px', cursor:'pointer', display:'none', boxShadow:'0 10px 20px -5px rgba(124,58,237,0.4)' },
  sidebar: { width:'280px', background:'linear-gradient(180deg, #2e1065 0%, #4c1d95 100%)', color:'#fff', display:'flex', flexDirection:'column', padding:'32px 20px', position:'fixed', height:'100vh', overflowY:'auto', zIndex:99999, boxShadow:'10px 0 30px -10px rgba(0,0,0,0.2)' },
  logoWrapper: { display:'flex', alignItems:'center', gap:'12px', marginBottom:'24px', padding:'0 8px' },
  logoIcon: { width:'40px', height:'40px', background:'rgba(255,255,255,0.1)', borderRadius:'12px', display:'flex', alignItems:'center', justifyContent:'center', color:'#fff' },
  logoText: { fontSize:'1.4rem', fontWeight:'800', letterSpacing:'-0.02em', color:'#fff' },
  logoAccent: { color:'#c4b5fd' },
  principalBadge: { background:'rgba(255,255,255,0.05)', borderRadius:'30px', padding:'8px 16px', margin:'0 8px 32px 8px', fontSize:'12px', color:'#c4b5fd', display:'flex', alignItems:'center', gap:'8px', border:'1px solid rgba(255,255,255,0.1)', backdropFilter:'blur(10px)', position:'relative' },
  liveIndicator: { width:'8px', height:'8px', borderRadius:'50%', background:'#22c55e', animation:'pulse 1.5s infinite', position:'absolute', right:'12px' },
  nav: { flex:1, display:'flex', flexDirection:'column', gap:'6px' },
  navBtn: { width:'100%', display:'flex', alignItems:'center', gap:'14px', padding:'14px 18px', borderRadius:'16px', border:'none', cursor:'pointer', backgroundColor:'transparent', color:'#c4b5fd', fontWeight:'600', textAlign:'left', fontSize:'15px', position:'relative', transition:'all 0.3s ease' },
  navBtnActive: { backgroundColor:'rgba(124,58,237,0.15)', color:'#fff', boxShadow:'inset 0 2px 4px rgba(0,0,0,0.1)' },
  navBadge: { background:'#7c3aed', color:'#fff', padding:'2px 8px', borderRadius:'30px', fontSize:'11px', fontWeight:'700' },
  activeIndicator: { position:'absolute', left:0, top:'25%', width:'4px', height:'50%', background:'linear-gradient(180deg, #7c3aed, #a78bfa)', borderRadius:'0 4px 4px 0' },
  logoutBtn: { display:'flex', alignItems:'center', gap:'12px', padding:'16px 18px', background:'rgba(239,68,68,0.1)', color:'#f87171', border:'1px solid rgba(239,68,68,0.2)', cursor:'pointer', borderRadius:'16px', fontWeight:'700', fontSize:'15px', marginTop:'20px', transition:'all 0.3s ease' },
  main: { flex:1, padding:'48px', marginLeft:'280px', marginRight:'320px', overflowY:'auto', zIndex:5, position:'relative', transition:'margin-right 0.35s cubic-bezier(0.4,0,0.2,1)' },
  mainCollapsed: { flex:1, padding:'48px', marginLeft:'280px', marginRight:'24px', overflowY:'auto', zIndex:5, position:'relative', transition:'margin-right 0.35s cubic-bezier(0.4,0,0.2,1)' },
  header: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'40px' },
  headerActions: { display:'flex', gap:'12px', alignItems:'center' },
  title: { fontSize:'2.2rem', fontWeight:'800', margin:0, background:'linear-gradient(135deg, #2e1065, #4c1d95)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', letterSpacing:'-0.02em' },
  subtitle: { color:'#64748b', marginTop:'6px', fontSize:'1rem', fontWeight:'500' },
  dateBadge: { background:'#fff', padding:'12px 24px', borderRadius:'30px', border:'1px solid #e2e8f0', fontSize:'0.95rem', fontWeight:'700', color:'#1e293b', display:'flex', alignItems:'center', gap:'8px', boxShadow:'0 4px 10px -2px rgba(0,0,0,0.05)', cursor:'pointer', transition:'all 0.2s ease' },
  refreshBadge: { background:'#fff', padding:'12px 20px', borderRadius:'30px', border:'1px solid #e2e8f0', fontSize:'0.9rem', fontWeight:'600', color:'#7c3aed', display:'flex', alignItems:'center', gap:'8px', boxShadow:'0 4px 10px -2px rgba(0,0,0,0.05)', cursor:'pointer', transition:'all 0.2s ease' },
  overviewContainer: { display:'flex', flexDirection:'column', gap:'32px' },
  statsGrid: { display:'grid', gridTemplateColumns:'repeat(3, 1fr)', gap:'24px' },
  metricCard: { backgroundColor:'#fff', padding:'20px', borderRadius:'24px', border:'1px solid #e2e8f0', display:'flex', alignItems:'center', gap:'16px', transition:'all 0.3s ease', boxShadow:'0 4px 6px -2px rgba(0,0,0,0.05)' },
  metricIconWrapper: (color) => ({ width:'52px', height:'52px', borderRadius:'18px', background:`${color}15`, display:'flex', alignItems:'center', justifyContent:'center', color }),
  metricContent: { flex:1 },
  metricLabel: { margin:0, fontSize:'0.85rem', fontWeight:'600', color:'#64748b', letterSpacing:'0.02em' },
  metricValue: { margin:'2px 0', fontSize:'1.8rem', fontWeight:'800' },
  metricTrend: { fontSize:'0.7rem', fontWeight:'600', color:'#22c55e', background:'#dcfce7', padding:'2px 8px', borderRadius:'30px', display:'inline-block' },
  chartCard: { backgroundColor:'#fff', padding:'28px', borderRadius:'32px', border:'1px solid #e2e8f0', boxShadow:'0 10px 25px -5px rgba(0,0,0,0.05)' },
  chartHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'20px' },
  chartTitle: { margin:0, fontWeight:'700', fontSize:'1.2rem', color:'#0f172a' },
  chartSubtitle: { margin:'4px 0 0', fontSize:'0.85rem', color:'#64748b' },
  chartControls: { display:'flex', alignItems:'center', gap:'8px', background:'#f1f5f9', padding:'6px 14px', borderRadius:'30px' },
  chartLive: { fontSize:'0.75rem', fontWeight:'700', color:'#7c3aed', letterSpacing:'0.05em' },
  bottomGrid: { display:'grid', gridTemplateColumns:'1fr 1fr', gap:'24px' },
  quickActionsCard: { backgroundColor:'#fff', padding:'24px', borderRadius:'24px', border:'1px solid #e2e8f0' },
  recentActivityCard: { backgroundColor:'#fff', padding:'24px', borderRadius:'24px', border:'1px solid #e2e8f0' },
  sectionHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'16px' },
  sectionTitle: { margin:0, fontWeight:'700', fontSize:'1rem', color:'#0f172a' },
  actionsGrid: { display:'grid', gridTemplateColumns:'repeat(2, 1fr)', gap:'12px' },
  actionButton: { background:'#f8fafc', border:'1px solid #e2e8f0', padding:'12px', borderRadius:'16px', cursor:'pointer', fontWeight:'600', fontSize:'0.85rem', color:'#1e293b', display:'flex', alignItems:'center', justifyContent:'center', gap:'8px', transition:'all 0.2s ease' },
  activityList: { display:'flex', flexDirection:'column', gap:'12px' },
  activityItem: { display:'flex', gap:'12px', alignItems:'flex-start', padding:'8px 0', borderBottom:'1px solid #f1f5f9' },
  activityIcon: { width:'24px', height:'24px', borderRadius:'8px', background:'#ede9fe', display:'flex', alignItems:'center', justifyContent:'center' },
  activityContent: { flex:1 },
  activityText: { margin:0, fontSize:'0.85rem', fontWeight:'600', color:'#1e293b' },
  activityTime: { fontSize:'0.7rem', color:'#94a3b8' },
  tableCard: { backgroundColor:'#fff', borderRadius:'32px', border:'1px solid #e2e8f0', overflow:'hidden', boxShadow:'0 10px 25px -5px rgba(0,0,0,0.05)' },
  tableHeader: { padding:'24px 28px', display:'flex', justifyContent:'space-between', alignItems:'center', borderBottom:'1px solid #f1f5f9' },
  tableTitle: { margin:0, fontWeight:'700', fontSize:'1.2rem', color:'#0f172a', textTransform:'capitalize' },
  tableSubtitle: { margin:'4px 0 0', fontSize:'0.85rem', color:'#64748b' },
  tableActions: { display:'flex', gap:'12px', alignItems:'center' },
  addBtn: { background:'linear-gradient(135deg, #7c3aed, #a78bfa)', color:'#fff', border:'none', padding:'12px 24px', borderRadius:'30px', cursor:'pointer', fontWeight:'700', fontSize:'0.9rem', display:'flex', alignItems:'center', gap:'8px', transition:'all 0.3s ease', boxShadow:'0 10px 20px -8px rgba(124,58,237,0.5)' },
  exportBtn: { background:'#f1f5f9', border:'none', width:'44px', height:'44px', borderRadius:'50%', cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', color:'#64748b', transition:'all 0.2s ease' },
  table: { width:'100%', borderCollapse:'collapse', minWidth:'800px' },
  tableHeadRow: { borderBottom:'1px solid #e2e8f0' },
  th: { padding:'18px 28px', backgroundColor:'#f8fafc', color:'#64748b', fontSize:'0.75rem', fontWeight:'800', letterSpacing:'0.05em', textAlign:'left' },
  tableRow: { borderBottom:'1px solid #f1f5f9', transition:'background 0.2s ease' },
  tdName: { padding:'20px 28px', fontWeight:'700', color:'#0f172a', fontSize:'0.95rem' },
  td: { padding:'20px 28px', color:'#64748b', fontSize:'0.9rem', fontWeight:'500' },
  statusBadge: { padding:'4px 10px', borderRadius:'30px', fontSize:'0.7rem', fontWeight:'700', textTransform:'uppercase', display:'inline-block' },
  actionGroup: { display:'flex', gap:'8px', justifyContent:'flex-end' },
  iconBtn: { background:'none', border:'none', color:'#64748b', cursor:'pointer', padding:'8px', borderRadius:'10px', transition:'all 0.2s ease', display:'inline-flex', alignItems:'center', justifyContent:'center' },
  deleteBtn: { background:'none', border:'none', color:'#ef4444', cursor:'pointer', padding:'8px', borderRadius:'10px', transition:'all 0.2s ease', display:'inline-flex', alignItems:'center', justifyContent:'center' },
  approveBtn: { background:'#22c55e', color:'#fff', border:'none', padding:'8px 16px', borderRadius:'30px', fontWeight:'600', fontSize:'0.8rem', cursor:'pointer', display:'inline-flex', alignItems:'center', gap:'6px', transition:'all 0.2s ease', boxShadow:'0 4px 10px -2px rgba(34,197,94,0.3)' },
  rejectBtn: { background:'#ef4444', color:'#fff', border:'none', padding:'8px 16px', borderRadius:'30px', fontWeight:'600', fontSize:'0.8rem', cursor:'pointer', display:'inline-flex', alignItems:'center', gap:'6px', transition:'all 0.2s ease', boxShadow:'0 4px 10px -2px rgba(239,68,68,0.3)' },
  rightPanel: { width:'320px', backgroundColor:'#fff', borderLeft:'1px solid #e2e8f0', padding:'40px 24px', position:'fixed', right:0, top:0, height:'100vh', overflowY:'auto', zIndex:99999, boxShadow:'-10px 0 30px -10px rgba(0,0,0,0.05)' },
  profileCard: { textAlign:'center', background:'linear-gradient(135deg, #f8fafc, #ffffff)', padding:'32px 20px', borderRadius:'32px', border:'1px solid #e2e8f0', marginBottom:'24px' },
  avatar: { width:'80px', height:'80px', color:'#fff', borderRadius:'28px', margin:'0 auto 16px', display:'flex', alignItems:'center', justifyContent:'center', fontSize:'32px', fontWeight:'800', boxShadow:'0 15px 30px -10px rgba(124,58,237,0.3)' },
  profileName: { margin:'0 0 8px', fontSize:'1.2rem', fontWeight:'800', color:'#0f172a' },
  roleBadge: { padding:'6px 16px', borderRadius:'30px', fontSize:'0.8rem', fontWeight:'700', background:'#ede9fe', color:'#6d28d9', display:'inline-block' },
  profileStats: { marginTop:'20px', paddingTop:'16px', borderTop:'1px solid #f1f5f9', display:'flex', justifyContent:'space-around' },
  profileStat: { textAlign:'center' },
  profileStatLabel: { fontSize:'0.75rem', color:'#64748b', fontWeight:'600' },
  profileStatValue: { fontSize:'1.1rem', fontWeight:'800', color:'#7c3aed' },
  section: { marginTop:'24px' },
  performersList: { display:'flex', flexDirection:'column', gap:'12px' },
  performerItem: { display:'flex', alignItems:'center', gap:'12px', padding:'10px', background:'#f8fafc', borderRadius:'16px' },
  performerAvatar: { width:'36px', height:'36px', borderRadius:'12px', background:'#7c3aed', color:'#fff', display:'flex', alignItems:'center', justifyContent:'center', fontWeight:'700', fontSize:'14px' },
  performerInfo: { flex:1 },
  performerName: { margin:0, fontSize:'0.9rem', fontWeight:'700', color:'#0f172a' },
  performerRole: { fontSize:'0.7rem', color:'#64748b' },
  performerBadge: { padding:'4px 8px', background:'#fef3c7', borderRadius:'30px' },
  pendingList: { display:'flex', flexDirection:'column', gap:'12px' },
  pendingItem: { display:'flex', alignItems:'center', gap:'12px', padding:'10px', background:'#f8fafc', borderRadius:'16px' },
  pendingAvatar: { width:'36px', height:'36px', borderRadius:'12px', background:'#f97316', color:'#fff', display:'flex', alignItems:'center', justifyContent:'center', fontWeight:'700', fontSize:'14px' },
  pendingInfo: { flex:1 },
  pendingName: { margin:0, fontSize:'0.9rem', fontWeight:'700', color:'#0f172a' },
  pendingTime: { fontSize:'0.7rem', color:'#64748b' },
  viewAllBtn: { background:'none', border:'1px solid #e2e8f0', padding:'10px', borderRadius:'16px', cursor:'pointer', fontWeight:'600', fontSize:'0.85rem', color:'#7c3aed', width:'100%', transition:'all 0.2s ease' },
  systemHealth: { marginTop:'24px', padding:'16px', background:'#f8fafc', borderRadius:'20px' },
  healthItem: { display:'flex', justifyContent:'space-between', alignItems:'center', padding:'8px 0' },
  healthLabel: { fontSize:'0.85rem', color:'#64748b', fontWeight:'600' },
  healthValue: { fontSize:'0.85rem', fontWeight:'700', color:'#22c55e', display:'flex', alignItems:'center', gap:'6px' },
  healthDot: { width:'8px', height:'8px', borderRadius:'50%', background:'#22c55e', animation:'pulse 2s infinite' },
  healthSelect: { border:'1px solid #e2e8f0', borderRadius:'20px', padding:'4px 8px', fontSize:'0.8rem', fontWeight:'600', color:'#7c3aed', background:'#fff', cursor:'pointer' },
  tabToggle: { display:'flex', background:'#f1f5f9', padding:'4px', borderRadius:'12px', border:'1px solid #e2e8f0' },
  toggleItem: { padding:'6px 16px', borderRadius:'8px', border:'none', background:'transparent', fontSize:'0.85rem', fontWeight:'700', color:'#64748b', cursor:'pointer', transition:'all 0.2s ease' },
  toggleActive: { background:'#fff', color:'#7c3aed', boxShadow:'0 4px 6px -1px rgba(0,0,0,0.05)' },
  timetableMatrixContainer: { overflowX:'auto', padding:'10px 0' },
  timetableGrid: { display:'grid', gridTemplateColumns:'repeat(7, 1fr)', gap:'20px', padding:'20px', background:'#f8fafc', borderRadius:'24px', minWidth:'1200px' },
  dayColumn: { display:'flex', flexDirection:'column', gap:'12px', minWidth:'160px' },
  dayTitle: { fontSize:'0.9rem', fontWeight:'800', color:'#1e293b', textAlign:'center', padding:'10px', background:'#fff', borderRadius:'16px', boxShadow:'0 4px 6px -1px rgba(0,0,0,0.05)', border:'1px solid #f1f5f9' },
  dayEntries: { display:'flex', flexDirection:'column', gap:'12px' },
  timetableEntry: { background:'#fff', padding:'14px', borderRadius:'20px', boxShadow:'0 4px 12px rgba(0,0,0,0.03)', border:'1px solid #f1f5f9', position:'relative', transition:'all 0.3s ease', display:'flex', flexDirection:'column', minHeight:'120px' },
  entryMain: { flex:1 },
  entryCourse: { fontSize:'0.9rem', fontWeight:'800', color:'#0f172a', margin:'0 0 8px 0', lineHeight:'1.2' },
  entryMeta: { fontSize:'0.75rem', fontWeight:'700', color:'#7c3aed', display:'flex', alignItems:'center', gap:'6px', margin:'0 0 10px 0' },
  entryBadgeContainer: { display:'flex', flexDirection:'column', gap:'4px' },
  entryMiniBadge: { fontSize:'0.7rem', color:'#64748b', background:'#f1f5f9', padding:'2px 8px', borderRadius:'6px', display:'flex', alignItems:'center', gap:'4px', width:'fit-content', fontWeight:'600' },
  entryDetail: { fontSize:'0.7rem', color:'#94a3b8', margin:'0', fontWeight:'500' },
  entryDelete: { position:'absolute', top:'12px', right:'12px', background:'#fee2e2', color:'#ef4444', border:'none', width:'28px', height:'28px', borderRadius:'8px', display:'flex', alignItems:'center', justifyContent:'center', cursor:'pointer', opacity:0, transition:'all 0.2s ease' },
  noEntries: { fontSize:'0.75rem', color:'#94a3b8', textAlign:'center', fontStyle:'italic', marginTop:'10px', padding:'20px', background:'#f8fafc', borderRadius:'16px', border:'1px dashed #e2e8f0' },
  historyLogContainer: { padding:'20px' },
  historyList: { display:'flex', flexDirection:'column', gap:'16px', maxWidth:'900px', margin:'0 auto' },
  historyItem: { display:'flex', gap:'20px', padding:'20px', background:'#fff', borderRadius:'24px', border:'1px solid #f1f5f9', transition:'all 0.2s ease', boxShadow:'0 4px 12px rgba(0,0,0,0.02)' },
  historyDateBadge: { width:'60px', height:'60px', background:'#f5f3ff', borderRadius:'16px', display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center', color:'#7c3aed', flexShrink:0 },
  hDateDay: { fontSize:'1.2rem', fontWeight:'800', lineHeight:'1' },
  hDateMonth: { fontSize:'0.7rem', fontWeight:'700', textTransform:'uppercase' },
  historyContent: { flex:1 },
  hRow: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'6px' },
  hTitle: { fontSize:'1.05rem', fontWeight:'800', color:'#0f172a', margin:0 },
  hStatusBadge: { fontSize:'0.7rem', fontWeight:'800', background:'#dcfce7', color:'#166534', padding:'4px 10px', borderRadius:'20px' },
  hSub: { fontSize:'0.9rem', color:'#64748b', margin:'0 0 12px 0' },
  hMeta: { display:'flex', gap:'20px' },
  hMetaItem: { display:'flex', alignItems:'center', gap:'6px', fontSize:'0.8rem', color:'#94a3b8', fontWeight:'600' },
  emptyState: { textAlign:'center', padding:'60px 20px', color:'#94a3b8' },
  emptyTableCell: { padding:'32px', textAlign:'center', color:'#94a3b8', fontSize:'0.9rem' },
  modalFooter: { padding:'20px 24px', borderTop:'1px solid #f1f5f9', display:'flex', justifyContent:'flex-end', gap:'12px', background:'#f8fafc' },
  submitBtn: { padding:'10px 20px', borderRadius:'12px', border:'none', fontWeight:'700', cursor:'pointer', transition:'all 0.2s ease', fontSize:'14px', color:'#fff' },
  modalOverlay: { position:'fixed', inset:0, background:'rgba(15,23,42,0.7)', backdropFilter:'blur(8px)', display:'flex', alignItems:'center', justifyContent:'center', zIndex:9999, animation:'fadeIn 0.2s ease' },
  modal: { background:'#fff', padding:'40px', borderRadius:'40px', width:'480px', maxHeight:'90vh', overflowY:'auto', boxShadow:'0 50px 70px -20px rgba(0,0,0,0.3)' },
  modalHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'24px' },
  modalTitle: { fontWeight:'800', fontSize:'1.5rem', color:'#0f172a', letterSpacing:'-0.02em', margin:0 },
  modalClose: { background:'#f1f5f9', border:'none', width:'40px', height:'40px', borderRadius:'50%', fontSize:'1.5rem', cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', color:'#64748b', transition:'all 0.2s ease' },
  modalForm: { display:'flex', flexDirection:'column', gap:'20px' },
  inputGroup: { display:'flex', flexDirection:'column', gap:'6px' },
  inputLabel: { fontSize:'0.85rem', fontWeight:'700', color:'#475569', marginLeft:'4px' },
  input: { padding:'14px 18px', borderRadius:'20px', border:'2px solid #f1f5f9', outline:'none', width:'100%', fontSize:'0.95rem', fontWeight:'500', transition:'all 0.2s ease', boxSizing:'border-box', fontFamily:"'Plus Jakarta Sans', sans-serif" },
  modalActions: { display:'flex', gap:'12px', marginTop:'12px' },
  cancelBtn: { flex:1, padding:'14px', background:'#f1f5f9', border:'none', borderRadius:'30px', cursor:'pointer', fontWeight:'700', color:'#64748b', fontSize:'0.95rem', transition:'all 0.2s ease' },
  saveBtn: { flex:2, padding:'14px', background:'linear-gradient(135deg, #7c3aed, #a78bfa)', color:'#fff', border:'none', borderRadius:'30px', cursor:'pointer', fontWeight:'700', fontSize:'0.95rem', transition:'all 0.2s ease', boxShadow:'0 10px 20px -8px rgba(124,58,237,0.5)' },
  loadingContainer: { height:'100vh', display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center', gap:'16px', background:'#f8fafc' },
  loadingSpinner: { width:'50px', height:'50px', border:'4px solid #e2e8f0', borderTop:'4px solid #7c3aed', borderRadius:'50%', animation:'spin 1s linear infinite' },
  loadingText: { fontSize:'1rem', fontWeight:'600', color:'#7c3aed' },
  row: { display:'flex', gap:'16px' },
  flex1: { flex:1, display:'flex', flexDirection:'column', gap:'6px' },
};
